docs_dir: 'source'
site_dir: 'docs'
site_name: 'Blocknet Documentation'
site_description: 'Blocknet is a blockchain interoperability protocol that enables communication, interaction, and exchange between different public and private blockchains.'
site_author: 'Blocknet'
use_directory_urls: true # do not change this, it will break all links
theme: 
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/blocknet-logo-128.svg'
  font: false
  icon:
    repo: fontawesome/brands/github
extra:
  head:
    - type: link
      attrs:
        - rel: profile
          href: http://gmpg.org/xfn/11
    - type: meta
      attrs:
        - name: theme-color
          content: '#dddfeb'
    - type: link
      attrs:
        - rel: shortlink
          href: '{{ config.site_url }}'
    - type: link
      attrs:
        - rel: dns-prefetch
          href: //www.blocknet.co
    - type: link
      attrs:
        - rel: apple-touch-icon
          sizes: 180x180
          href: /img/apple-touch-icon.png
    - type: link
      attrs:
        - rel: icon
          type: image/png
          sizes: 32x32
          href: /img/favicon-32x32.png
    - type: link
      attrs:
        - rel: icon
          type: image/png
          sizes: 16x16
          href: /img/favicon-16x16.png
    - type: link
      attrs:
        - rel: mask-icon
          href: https://www.blocknet.co/wp-content/themes/blocknet/includes/img/favicon/safari-pinned-tab.svg
          color: '#051937'
    - type: meta
      attrs:
        - name: msapplication-TileColor
          content: '#dddfeb'
    - type: meta
      attrs:
        - property: og:locale
          content: en_US
    - type: meta
      attrs:
        - property: og:type
          content: website
    - type: meta
      attrs:
        - property: og:title
          content: >-
            {{ (page.meta.title if page and page.meta and page.meta.title else (page.title ~ ' - ' if page and page.title else '') ~ config.site_name) }}
    - type: meta
      attrs:
        - property: og:description
          content: >-
            {{ page.meta.description if page and page.meta and page.meta.description else config.site_description }}
    - type: meta
      attrs:
        - property: og:url
          content: '{{ config.site_url }}'
    - type: meta
      attrs:
        - property: og:site_name
          content: '{{ config.site_name }}'
    - type: meta
      attrs:
        - property: og:image
          content: /img/blocknet.png
    - type: meta
      attrs:
        - property: og:image:secure_url
          content: /img/blocknet.png
    - type: meta
      attrs:
        - name: twitter:card
          content: summary_large_image
    - type: meta
      attrs:
        - name: twitter:description
          content: >-
            {{ page.meta.description if page and page.meta and page.meta.description else config.site_description }}
    - type: meta
      attrs:
        - name: twitter:title
          content: >-
            {{ (page.meta.title if page and page.meta and page.meta.title else (page.title ~ ' - ' if page and page.title else '') ~ config.site_name) }}
    - type: meta
      attrs:
        - name: twitter:image
          content: /img/blocknet.png
  social:
    - icon: material/email
      link: 'mailto:contact@blocknet.co'
    - icon: material/github
      link: 'https://github.com/blocknetdx/'
    - icon: simple/discord
      link: 'https://discord.gg/vGa7GeCu8B'
    - icon: simple/telegram
      link: 'https://t.me/Blocknet'
    - icon: simple/medium
      link: 'https://medium.com/@theblocknetchannel'
    - icon: material/facebook
      link: 'https://en-gb.facebook.com/theblocknet/'
    - icon: material/twitter
      link: 'https://twitter.com/The_Blocknet'
    - icon: material/reddit
      link: 'https://www.reddit.com/r/theblocknet/'
    - icon: material/youtube
      link: 'https://www.youtube.com/c/TheBlocknet'
    - icon: material/instagram
      link: 'https://www.instagram.com/the_blocknet/'
    - icon: material/linkedin
      link: 'https://www.linkedin.com/company/the-blocknet/'
  snode_collateral: '5000'
  proposal_link: 'http://blocknetdx.forumotion.com/f3-self-funding-proposals'
  newsletter_general: 'http://eepurl.com/c5OJMj'
  newsletter_snodes: 'http://eepurl.com/dq-ElD'
  newsletter_developers: 'http://eepurl.com/dDjhYH'
  discord: 'https://discord.gg/vGa7GeCu8B'
  blockdx_releases: 'https://github.com/blocknetdx/blockdx-ui/releases'
  docs_repo: 'blocknetdx/documentation'
site_url: 'https://docs.blocknet.org/'
repo_url: 'https://github.com/blocknetdx/documentation'
repo_name: 'blocknetdx/documentation'
edit_uri: '/blocknetdx/documentation/edit/master/docs/'
markdown_extensions:
  - codehilite
  - markdown.extensions.footnotes
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.extra
  - meta
  - markdown.extensions.toc:
      permalink: True
  - pymdownx.snippets:
      base_path: 'snippets/'
      encoding: 'utf-8'
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - js/main.js
extra_css:
  - css/fonts.css
  - css/style.css
nav:
- 'Home': 'index.md'
# - 'Dashboard': 'dashboard.md'
- 'Project':
  - 'Introduction': 'project/introduction.md'
  - 'Exchanges': 'project/exchanges.md'
  - "Whitepaper <i class='fa fa-external-link' aria-hidden='true'></i>": 'project/blocknet-whitepaper.pdf'
  - 'Roadmap': 'project/roadmap.md'
  - 'Governance': 'governance/introduction.md'
  - 'Contributors': 'project/contributors.md'
  - 'Social': 'project/social.md'
  # - 'Financials': 'project/financials.md'
  # - 'FAQ': 'project/faq.md'
- 'Blockchain':
  - 'Introduction': 'blockchain/introduction.md'
  # - 'Tokenomics': 'blockchain/tokenomics.md'
  - 'Exchanges': 'project/exchanges.md'
  # - 'aaBLOCK': 'blockchain/aablock.md'
  # - 'aBLOCK': 'blockchain/ablock.md'
  - 'Explorers': 'blockchain/explorers.md'
- 'Protocol':
  - 'XBridge':
    - 'Introduction': 'protocol/xbridge/introduction.md'
    - 'Fees': 'protocol/xbridge/fees.md'
    # - 'Design': 'protocol/xbridge/design.md'
    - 'Compatibility': 'protocol/xbridge/compatibility.md'
    # - 'Standards': 'protocol/xbridge/standards.md'
    # - 'Use Cases': 'protocol/xbridge/use-cases.md'
    - 'Setup': 'protocol/xbridge/setup.md'
  - 'XRouter':
    - 'Introduction': 'protocol/xrouter/introduction.md'
    # - 'Compatibility': 'protocol/xrouter/compatibility.md'
    # - 'Standards': 'protocol/xrouter/standards.md'
    # - 'Use Cases': 'protocol/xrouter/introduction/#use-cases'
    # - 'Setup': 'protocol/xrouter/setup.md'
  - 'XCloud':
    - 'Introduction': 'protocol/xcloud/introduction.md'
    # - 'Compatibility': 'protocol/xcloud/compatibility.md'
  # - "Use Cases <i class='fa fa-external-link' aria-hidden='true'></i>": 'project/blocknet-business-use-cases.pdf'
  - "API Docs <i class='fa fa-external-link' aria-hidden='true'></i>": 'https://api.blocknet.org/'
- 'Blocknet Wallet':
  - 'Getting Started': 'wallet/setup.md'
  - 'Installation': 'wallet/installation.md'
  # - 'Updating': 'wallet/updating.md'
  - 'Syncing': 'wallet/syncing.md'
  - 'Encrypt Wallet': 'wallet/encrypting.md'
  - 'Backup/Restore': 'wallet/backup-restore.md'
  - 'Staking': 'wallet/staking.md'
  - 'Send Funds': 'wallet/send-funds.md'
  - 'Coin Control': 'wallet/coin-control.md'
  - 'Fix Wrong Balance': wallet/fix-wrong-balance.md
  - 'Fork Management': 'wallet/forking.md'
  # - 'Peers': 'wallet/peers.md'
  - 'Lock/Unlock': 'wallet/lock-unlock.md'
  # - 'Balances': 'wallet/balances.md'
  # - 'Addresses': 'wallet/addresses.md'
  # - 'Receive Funds': 'wallet/addresses/#receiving-addresses'
  # - 'Transactions': 'wallet/transaction-details.md'
  # - 'Debug Console': 'wallet/debug-console.md'
  # - 'Troubleshooting': 'wallet/troubleshooting.md'
  # - 'Security': 'wallet/security.md'
  - 'Integration': 'wallet/integration.md'
  - 'Log Files': 'wallet/log-files.md'
- 'XLite':
  - 'Getting Started': 'xlite/setup.md'
  - 'Installation': 'xlite/installation.md'
  - 'Create, Backup & Restore': 'xlite/backup-and-restore.md'
  - 'Using BlockDX w/ XLite': 'xlite/blockdx-xlite.md'
  - 'Access Coin Daemons via RPC': 'xlite/access-coin-daemons-via-rpc.md'
  - 'Recover Private Keys': 'xlite/recover-private-keys.md'
  - 'Log Files': 'xlite/log-files.md'
- 'Block DX':
  - 'Introduction': 'blockdx/introduction.md'
  - 'Getting Started': 'blockdx/setup.md'
  - 'Installation': 'blockdx/installation.md'
  - 'Configuration': 'blockdx/configuration.md'
  # - 'Updating': 'blockdx/updating.md'
  # - 'Additional Setup':
    # - 'Create Legacy Address': 'blockdx/setup/create-legacy-address.md'
    # - 'Check Address Balance': 'wallet/address-balances.md'
    # - 'View Inputs': 'blockdx/setup/view-inputs.md'
    # - 'Create Inputs': 'wallet/create-inputs.md'
  - 'Trading': 'blockdx/trading.md'
  - 'Listings': 'blockdx/listings.md'
  - 'Fees': 'blockdx/fees.md'
  - 'Settings': 'blockdx/settings.md'
  - 'FAQ': 'blockdx/faq.md'
  - 'Log Files': 'blockdx/log-files.md'
  # - 'Troubleshooting': 'blockdx/troubleshooting.md'
- 'Service Nodes':
  - 'Introduction': 'service-nodes/introduction.md'
  - 'Setup': 'service-nodes/setup.md'
  - 'Operation': 'service-nodes/operation.md'
  - 'XBridge Configuration': 'service-nodes/xbridge-configuration.md'
  - 'XRouter Configuration': 'service-nodes/xrouter-configuration.md'
  - 'XCloud Configuration': 'service-nodes/xcloud-configuration.md'
  # - 'Config Manager': 'service-nodes/config-manager.md'
- 'Governance':
  - 'Introduction': 'governance/introduction.md'
  - 'Governance Model': 'governance/governance-model.md'
  # - 'Blocknet Improvement Process (BIP)': 'governance/blocknet-improvement-process-bip.md'
  - 'View Proposals': 'governance/view-proposals.md'
  - 'Create Proposal': 'governance/create-proposal.md'
  - 'Proposal Voting': 'governance/proposal-voting.md'
- 'Resources':
  - 'Interviews': 'resources/interviews.md'
  - "Branding Resources <i class='fa fa-external-link' aria-hidden='true'></i>": 'https://blocknet.co/brand-resources/'
  # - "Graphics Library <i class='fa fa-external-link' aria-hidden='true'></i>": 'https://drive.google.com/drive/folders/13Mke43Y0Lrc2SBTbSTOV71U4Jgjj9V75'
  - "Social Media Guideline <i class='fa fa-external-link' aria-hidden='true'></i>": 'project/social-media-guidelines.pdf'
# - 'Tools': 'tools.md'
- 'Developers':
  - "API <i class='fa fa-external-link' aria-hidden='true'></i>": 'https://api.blocknet.org'
  # - 'XBridge Setup': 'protocol/xbridge/setup.md'
  # - 'Blockchain Integration': 'developers/blockchain-integration.md'
  # - 'Service Integration': 'developers/service_integration.md'
  # - 'Project Ideas': 'developers/project-ideas.md'
  # - 'Repositories': 'developers/repositories.md'
  # - 'Tools': 'tools.md'
  # - 'Contributing': 'contributing/developers.md'
# - 'Support': 'support.md'
# - 'Contributing':
  # - 'Developers': 'contributing/developers.md'
  # - 'Community': 'contributing/community.md'
- 'About':
  - 'License': 'about/license.md'
- 'Glossary': 'resources/glossary.md'
copyright: If you wish to improve this site, please <a href="https://github.com/blocknetdx/documentation/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/blocknetdx/documentation/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>Blocknet Protocol 2022.
